# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player_brain/common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='player_brain/common.proto',
  package='player',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19player_brain/common.proto\x12\x06player\"\xe3\x01\n\x05\x46ield\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\"\n\x04type\x18\x02 \x01(\x0e\x32\x14.player.Field.FVType\x12\x0e\n\x06u_type\x18\x03 \x01(\x05\x12\n\n\x02iv\x18\x04 \x03(\x03\x12\n\n\x02\x64v\x18\x05 \x03(\x01\x12\n\n\x02\x62v\x18\x06 \x03(\x0c\"t\n\x06\x46VType\x12\x0c\n\x08\x46VT_LONG\x10\x00\x12\x12\n\x0e\x46VT_LONG_ARRAY\x10\x01\x12\x0e\n\nFVT_DOUBLE\x10\x02\x12\x14\n\x10\x46VT_DOUBLE_ARRAY\x10\x03\x12\r\n\tFVT_BYTES\x10\x04\x12\x13\n\x0f\x46VT_BYTES_ARRAY\x10\x05\"W\n\x06\x45ntity\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1d\n\x06\x66ields\x18\x02 \x03(\x0b\x32\r.player.Field\x12 \n\x08\x65ntities\x18\x03 \x03(\x0b\x32\x0e.player.Entityb\x06proto3')
)



_FIELD_FVTYPE = _descriptor.EnumDescriptor(
  name='FVType',
  full_name='player.Field.FVType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FVT_LONG', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FVT_LONG_ARRAY', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FVT_DOUBLE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FVT_DOUBLE_ARRAY', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FVT_BYTES', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FVT_BYTES_ARRAY', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=149,
  serialized_end=265,
)
_sym_db.RegisterEnumDescriptor(_FIELD_FVTYPE)


_FIELD = _descriptor.Descriptor(
  name='Field',
  full_name='player.Field',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='player.Field.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='player.Field.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='u_type', full_name='player.Field.u_type', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iv', full_name='player.Field.iv', index=3,
      number=4, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dv', full_name='player.Field.dv', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bv', full_name='player.Field.bv', index=5,
      number=6, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FIELD_FVTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=265,
)


_ENTITY = _descriptor.Descriptor(
  name='Entity',
  full_name='player.Entity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='player.Entity.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fields', full_name='player.Entity.fields', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entities', full_name='player.Entity.entities', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=354,
)

_FIELD.fields_by_name['type'].enum_type = _FIELD_FVTYPE
_FIELD_FVTYPE.containing_type = _FIELD
_ENTITY.fields_by_name['fields'].message_type = _FIELD
_ENTITY.fields_by_name['entities'].message_type = _ENTITY
DESCRIPTOR.message_types_by_name['Field'] = _FIELD
DESCRIPTOR.message_types_by_name['Entity'] = _ENTITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Field = _reflection.GeneratedProtocolMessageType('Field', (_message.Message,), dict(
  DESCRIPTOR = _FIELD,
  __module__ = 'player_brain.common_pb2'
  # @@protoc_insertion_point(class_scope:player.Field)
  ))
_sym_db.RegisterMessage(Field)

Entity = _reflection.GeneratedProtocolMessageType('Entity', (_message.Message,), dict(
  DESCRIPTOR = _ENTITY,
  __module__ = 'player_brain.common_pb2'
  # @@protoc_insertion_point(class_scope:player.Entity)
  ))
_sym_db.RegisterMessage(Entity)


# @@protoc_insertion_point(module_scope)
