# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import player_brain_pb2 as player__brain_dot_player__brain__pb2


class PlayerBrainStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RpcCall = channel.unary_unary(
        '/player.PlayerBrain/RpcCall',
        request_serializer=player__brain_dot_player__brain__pb2.Request.SerializeToString,
        response_deserializer=player__brain_dot_player__brain__pb2.Response.FromString,
        )


class PlayerBrainServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RpcCall(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PlayerBrainServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RpcCall': grpc.unary_unary_rpc_method_handler(
          servicer.RpcCall,
          request_deserializer=player__brain_dot_player__brain__pb2.Request.FromString,
          response_serializer=player__brain_dot_player__brain__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'player.PlayerBrain', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
