# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player_brain/player_brain.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as player__brain_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='player_brain/player_brain.proto',
  package='player',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1fplayer_brain/player_brain.proto\x12\x06player\x1a\x19player_brain/common.proto\"\x9b\x01\n\x07Request\x12)\n\x07restart\x18\x01 \x01(\x0b\x32\x16.player.RequestRestartH\x00\x12\x31\n\x0bobservation\x18\x02 \x01(\x0b\x32\x1a.player.RequestObservationH\x00\x12\'\n\x06\x61\x63tion\x18\x03 \x01(\x0b\x32\x15.player.RequestActionH\x00\x42\t\n\x07request\"\xa0\x01\n\x08Response\x12*\n\x07restart\x18\x01 \x01(\x0b\x32\x17.player.ResponseRestartH\x00\x12\x32\n\x0bobservation\x18\x02 \x01(\x0b\x32\x1b.player.ResponseObservationH\x00\x12(\n\x06\x61\x63tion\x18\x03 \x01(\x0b\x32\x16.player.ResponseActionH\x00\x42\n\n\x08response\"\x10\n\x0eRequestRestart\"\x11\n\x0fResponseRestart\"5\n\x12RequestObservation\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.player.Entity\":\n\x13ResponseObservation\x12#\n\x0bobservation\x18\x01 \x01(\x0b\x32\x0e.player.Entity\"0\n\rRequestAction\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.player.Entity\"5\n\x0eResponseAction\x12#\n\x0bobservation\x18\x01 \x01(\x0b\x32\x0e.player.Entity2=\n\x0bPlayerBrain\x12.\n\x07RpcCall\x12\x0f.player.Request\x1a\x10.player.Response\"\x00\x62\x06proto3')
  ,
  dependencies=[player__brain_dot_common__pb2.DESCRIPTOR,])




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='player.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='restart', full_name='player.Request.restart', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observation', full_name='player.Request.observation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='player.Request.action', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='request', full_name='player.Request.request',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=71,
  serialized_end=226,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='player.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='restart', full_name='player.Response.restart', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observation', full_name='player.Response.observation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='player.Response.action', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='response', full_name='player.Response.response',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=229,
  serialized_end=389,
)


_REQUESTRESTART = _descriptor.Descriptor(
  name='RequestRestart',
  full_name='player.RequestRestart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=407,
)


_RESPONSERESTART = _descriptor.Descriptor(
  name='ResponseRestart',
  full_name='player.ResponseRestart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=409,
  serialized_end=426,
)


_REQUESTOBSERVATION = _descriptor.Descriptor(
  name='RequestObservation',
  full_name='player.RequestObservation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='player.RequestObservation.request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=428,
  serialized_end=481,
)


_RESPONSEOBSERVATION = _descriptor.Descriptor(
  name='ResponseObservation',
  full_name='player.ResponseObservation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='observation', full_name='player.ResponseObservation.observation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=483,
  serialized_end=541,
)


_REQUESTACTION = _descriptor.Descriptor(
  name='RequestAction',
  full_name='player.RequestAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='player.RequestAction.request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=543,
  serialized_end=591,
)


_RESPONSEACTION = _descriptor.Descriptor(
  name='ResponseAction',
  full_name='player.ResponseAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='observation', full_name='player.ResponseAction.observation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=593,
  serialized_end=646,
)

_REQUEST.fields_by_name['restart'].message_type = _REQUESTRESTART
_REQUEST.fields_by_name['observation'].message_type = _REQUESTOBSERVATION
_REQUEST.fields_by_name['action'].message_type = _REQUESTACTION
_REQUEST.oneofs_by_name['request'].fields.append(
  _REQUEST.fields_by_name['restart'])
_REQUEST.fields_by_name['restart'].containing_oneof = _REQUEST.oneofs_by_name['request']
_REQUEST.oneofs_by_name['request'].fields.append(
  _REQUEST.fields_by_name['observation'])
_REQUEST.fields_by_name['observation'].containing_oneof = _REQUEST.oneofs_by_name['request']
_REQUEST.oneofs_by_name['request'].fields.append(
  _REQUEST.fields_by_name['action'])
_REQUEST.fields_by_name['action'].containing_oneof = _REQUEST.oneofs_by_name['request']
_RESPONSE.fields_by_name['restart'].message_type = _RESPONSERESTART
_RESPONSE.fields_by_name['observation'].message_type = _RESPONSEOBSERVATION
_RESPONSE.fields_by_name['action'].message_type = _RESPONSEACTION
_RESPONSE.oneofs_by_name['response'].fields.append(
  _RESPONSE.fields_by_name['restart'])
_RESPONSE.fields_by_name['restart'].containing_oneof = _RESPONSE.oneofs_by_name['response']
_RESPONSE.oneofs_by_name['response'].fields.append(
  _RESPONSE.fields_by_name['observation'])
_RESPONSE.fields_by_name['observation'].containing_oneof = _RESPONSE.oneofs_by_name['response']
_RESPONSE.oneofs_by_name['response'].fields.append(
  _RESPONSE.fields_by_name['action'])
_RESPONSE.fields_by_name['action'].containing_oneof = _RESPONSE.oneofs_by_name['response']
_REQUESTOBSERVATION.fields_by_name['request'].message_type = player__brain_dot_common__pb2._ENTITY
_RESPONSEOBSERVATION.fields_by_name['observation'].message_type = player__brain_dot_common__pb2._ENTITY
_REQUESTACTION.fields_by_name['request'].message_type = player__brain_dot_common__pb2._ENTITY
_RESPONSEACTION.fields_by_name['observation'].message_type = player__brain_dot_common__pb2._ENTITY
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['RequestRestart'] = _REQUESTRESTART
DESCRIPTOR.message_types_by_name['ResponseRestart'] = _RESPONSERESTART
DESCRIPTOR.message_types_by_name['RequestObservation'] = _REQUESTOBSERVATION
DESCRIPTOR.message_types_by_name['ResponseObservation'] = _RESPONSEOBSERVATION
DESCRIPTOR.message_types_by_name['RequestAction'] = _REQUESTACTION
DESCRIPTOR.message_types_by_name['ResponseAction'] = _RESPONSEACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'player_brain.player_brain_pb2'
  # @@protoc_insertion_point(class_scope:player.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'player_brain.player_brain_pb2'
  # @@protoc_insertion_point(class_scope:player.Response)
  ))
_sym_db.RegisterMessage(Response)

RequestRestart = _reflection.GeneratedProtocolMessageType('RequestRestart', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTRESTART,
  __module__ = 'player_brain.player_brain_pb2'
  # @@protoc_insertion_point(class_scope:player.RequestRestart)
  ))
_sym_db.RegisterMessage(RequestRestart)

ResponseRestart = _reflection.GeneratedProtocolMessageType('ResponseRestart', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSERESTART,
  __module__ = 'player_brain.player_brain_pb2'
  # @@protoc_insertion_point(class_scope:player.ResponseRestart)
  ))
_sym_db.RegisterMessage(ResponseRestart)

RequestObservation = _reflection.GeneratedProtocolMessageType('RequestObservation', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTOBSERVATION,
  __module__ = 'player_brain.player_brain_pb2'
  # @@protoc_insertion_point(class_scope:player.RequestObservation)
  ))
_sym_db.RegisterMessage(RequestObservation)

ResponseObservation = _reflection.GeneratedProtocolMessageType('ResponseObservation', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEOBSERVATION,
  __module__ = 'player_brain.player_brain_pb2'
  # @@protoc_insertion_point(class_scope:player.ResponseObservation)
  ))
_sym_db.RegisterMessage(ResponseObservation)

RequestAction = _reflection.GeneratedProtocolMessageType('RequestAction', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTACTION,
  __module__ = 'player_brain.player_brain_pb2'
  # @@protoc_insertion_point(class_scope:player.RequestAction)
  ))
_sym_db.RegisterMessage(RequestAction)

ResponseAction = _reflection.GeneratedProtocolMessageType('ResponseAction', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEACTION,
  __module__ = 'player_brain.player_brain_pb2'
  # @@protoc_insertion_point(class_scope:player.ResponseAction)
  ))
_sym_db.RegisterMessage(ResponseAction)



_PLAYERBRAIN = _descriptor.ServiceDescriptor(
  name='PlayerBrain',
  full_name='player.PlayerBrain',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=648,
  serialized_end=709,
  methods=[
  _descriptor.MethodDescriptor(
    name='RpcCall',
    full_name='player.PlayerBrain.RpcCall',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PLAYERBRAIN)

DESCRIPTOR.services_by_name['PlayerBrain'] = _PLAYERBRAIN

# @@protoc_insertion_point(module_scope)
